/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\\public\\models\\Punk.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export function PunkGirl(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Punk.glb");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions["CharacterArmature|Idle_Neutral"].reset().fadeIn(0.5).play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <group name="Punk_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Punk_Body_1"
              geometry={nodes.Punk_Body_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Punk_Body_1.skeleton}
            />
            <skinnedMesh
              name="Punk_Body_2"
              geometry={nodes.Punk_Body_2.geometry}
              material={materials.Pink}
              skeleton={nodes.Punk_Body_2.skeleton}
            />
            <skinnedMesh
              name="Punk_Body_3"
              geometry={nodes.Punk_Body_3.geometry}
              material={materials.Black}
              skeleton={nodes.Punk_Body_3.skeleton}
            />
          </group>
          <group name="Punk_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Punk_Feet_1"
              geometry={nodes.Punk_Feet_1.geometry}
              material={materials.Black}
              skeleton={nodes.Punk_Feet_1.skeleton}
            />
            <skinnedMesh
              name="Punk_Feet_2"
              geometry={nodes.Punk_Feet_2.geometry}
              material={materials.Grey}
              skeleton={nodes.Punk_Feet_2.skeleton}
            />
          </group>
          <group name="Punk_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Punk_Head_1"
              geometry={nodes.Punk_Head_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Punk_Head_1.skeleton}
            />
            <skinnedMesh
              name="Punk_Head_2"
              geometry={nodes.Punk_Head_2.geometry}
              material={materials.Pink}
              skeleton={nodes.Punk_Head_2.skeleton}
            />
            <skinnedMesh
              name="Punk_Head_3"
              geometry={nodes.Punk_Head_3.geometry}
              material={materials.Black}
              skeleton={nodes.Punk_Head_3.skeleton}
            />
            <skinnedMesh
              name="Punk_Head_4"
              geometry={nodes.Punk_Head_4.geometry}
              material={materials.Hair_Brown}
              skeleton={nodes.Punk_Head_4.skeleton}
            />
            <skinnedMesh
              name="Punk_Head_5"
              geometry={nodes.Punk_Head_5.geometry}
              material={materials.Brown}
              skeleton={nodes.Punk_Head_5.skeleton}
            />
          </group>
          <group name="Punk_Legs" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Punk_Legs_1"
              geometry={nodes.Punk_Legs_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Punk_Legs_1.skeleton}
            />
            <skinnedMesh
              name="Punk_Legs_2"
              geometry={nodes.Punk_Legs_2.geometry}
              material={materials.Black}
              skeleton={nodes.Punk_Legs_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Punk.glb");
