/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\\public\\models\\Sticky_notes.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function StickyNotes(props) {
  const { nodes, materials } = useGLTF("/models/Sticky_notes.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.p000089795.geometry}
        material={materials["0.BaseMaterial"]}
      />
      <mesh
        geometry={nodes.c000174124.geometry}
        material={materials["0.BaseMaterial"]}
      />
      <mesh
        geometry={nodes.c000273834.geometry}
        material={materials["0.BaseMaterial"]}
      />
    </group>
  );
}

useGLTF.preload("/models/Sticky_notes.glb");
